apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: {{ .Chart.Name }}-{{ .Release.Name }}
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  namespace: default
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}-{{ .Release.Name }}
            port:
              number: {{ .Values.ports.service }}
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecret }}
